### ISSUE TITLE
Доп функционал #1

### ISSUE THREAD

**Issue by T1fon** [trpo2021/cw-ip-011_keyboardninja#3]
- Выбор режима печати (1 - только буквы; 2 - только цифры; 3 - буквы и цифры)
- Выбор уровня сложности для каждого режима:
- Для букв 1 - выводится 1 буква; 2 - выводится слово; 3 - выводится предложение
- Для цифр 1 - выводится 1 цифра; 2 - выводится число; 3 - выводится уравнение
- Для режима букв и цифр присутствует только один уровень сложности.

**Comment by maloooy** [comment]
Выбор режима печати настроен
